### PR TITLE
Added options-slot (Variant 2)

### PR DESCRIPTION
**Pull request by jbirtel**
I actually implemented this as an alternative to the first option. I actually like that one a bit better, because it is simpler imo. Link to the [Other PR](https://github.com/mskocik/svelecte/pull/250)

### CODE REVIEW

**Comment by mskocik** [comment]
Why the [example implementation](https://svelecte.vercel.app/examples#multiselect) for this use case (display icon in dropdown based on selection state) is not enough for you?

**Comment by jbirtel** [comment]
I already implemented it this way right now. However, I want to keep the search highlighting with the custom icon.

**Comment by mskocik** [comment]
You can provide custom icon and keep the highlighting image

The only downside is that you can't pass icon as svelte component. Is this what you are trying to do?

Can you show me in REPL what would you like to achieve?

**Comment by jbirtel** [comment]
How did you insert the icon here? I think it would be enough for now 🤔 However, I cannot not insert it as a string, but rather directly as HTML
```
<div class="multiselect-options" slot="option" let:item>
    <div class="icon-checkbox" class:selected={item.$selected}
            class:borderless={!autocompleteConfig.multiple}></div>
    <div class="sv-item--content">{@html item?.label || item?.text}</div>
</div>
```

Then, the icon is inserted in the css as background of the `.icon-checkbox::before`

**Comment by mskocik** [comment]
[REPL ](https://svelte.dev/repl/e40fc7998c8242e8b0094218b9337db9?version=4.2.19)with your slot and inserting icon as `::before` pseudo-element. Still I don't understand what is missing in current implementation 🤔

**Comment by jbirtel** [comment]
That is exactly how I implemented it. However, the highlighting of the search is missing in that case, so when I type „on“ I expext **On**e and Sec**on**d  to be highlighted. And I just wanted to get that status quo back with my implementation

**Comment by mskocik** [comment]
Oh yes, I got sidetracked from original issue to 'icon' discussion.

I am closing this as it is achievable by other means. And let's continue discussion on #250

**Pull request closed without merging**
