### PR TITLE
keepSelectionDuringSearch flag

### PR DESCRIPTION
**Pull request by petran123**
Added keepSelectionDuringSearch flag, which, when used along with keepSelectionInList = true, will also keep the selection in the list while searching.

### CODE REVIEW

**Comment by mskocik** [comment]
I am curious about your use case. Why do you want to see something, that's already selected?

**Comment by petran123** [comment]
I have multi select elements with high double digit options and it can get tedious for users to have to scroll to toggle multiple scattered options off. Especially in cases where options are not sorted alphabetically but based on ID or some other factor.

**Comment by mskocik** [comment]
Makes sense... But can you rework it to extend `SearchProps` instead of adding another property? That will be a better place for it.

**Comment by petran123** [comment]
Updated.

**Comment by mskocik** [comment]
I changed the name of it to `keepSelectionInList`. Released in `5.1.0`

**Pull request merged**
