### PR TITLE
do not reset value to null upon render

### PR DESCRIPTION
**Pull request by nosovk**

### CODE REVIEW

**Comment by nosovk** [comment]
do not merge that.
I have an issue, when binded storage is cleared upon svelecte mount.
I've tried to make a repro, but no luck:
https://svelte.dev/repl/e925be332237431f8aa56449fae73007?version=4.2.10
in common, it's my case, svelecte select value should persist upon page reload.
Value exist at component constructor, but missing in mount handler.
I was able to find out that value erased in a binding step, but wasn't able to find why.

**Comment by mskocik** [comment]
Try to reproduce in [sveltelab](http://sveltelab.dev/).

**Comment by nosovk** [comment]
thanks for the tool, it's much better for sveltekit repro:
https://www.sveltelab.dev/m0oixoktkkgbf18

but no luck, it works in repro.

**Comment by mskocik** [comment]
Okay, will try to reproduce it locally in sveltekit setup

**Comment by mskocik** [comment]
Please check your use-case in v4 and let me know.

**Comment by nosovk** [comment]
I've made a branch within v4 and dirty hack removed, but no luck, still got an issue

**Comment by nosovk** [comment]
https://cat-0-unhack.cat-land.pages.dev/en/form-test
here is a test form, values of selects saved to localstorage, and restored upon load

**Comment by mskocik** [comment]
It must be some different issue somewhere in your code 🤔 . I tried the example from sveltelab, basically this:

```svelte
<script>
	import Svelecte from 'svelecte';
  import { onMount } from "svelte";
  import { localWritable } from "@macfja/svelte-persistent-store";

	const options = [{value:'Hello'}, {value:'World'}, {value:'Svelte'}];
  let form = localWritable("svelecte", {
		value: null,
    name: ''
	});
	let initial = $form.value;
	let mounted = null;

	onMount(async () => {
		mounted = $form.value
	});
	
	function reload() {
		location.reload() 
	}
</script>

<hr>
Default item:
<Svelecte  {options} bind:value={$form.value} labelField="value"  valueField="value"/>
<br>
<input type="text" name="name" id="name" bind:value={$form.name}>
<p>Initial: {initial} </p>
<p>Mounted: {mounted}</p>
<p>Store: {$form.value}</p>
<button on:click={reload}>reload</button>
```

And here is my recording. It behaves as expected.

https://github.com/mskocik/svelecte/assets/25513620/42163fc3-29c4-4279-a15d-d98795c46c6a

So I am closing this PR (it's outdated anyway)

**Pull request closed without merging**
